const text = [
    'Her mom had warned her. She had been warned time and again, but she had refused to believe her. She had done everything right and she knew she would be rewarded for doing so with the promotion. So when the promotion was given to her main rival, it not only stung, it threw her belief system into disarray. It was her first big lesson in life, but not the last.',
    ' There once lived an old man and an old woman who were peasants and had to work hard to earn their daily bread.The old man used to go to fix fences and do other odd jobs for the farmers around, and while he was gone the old woman, his wife, did the work of the house and worked in their own little plot of land.',
    "She had come to the conclusion that you could tell a lot about a person by their ears.The way they stuck out and the size of the earlobes could give you wonderful insights into the person.Of course, she couldn't scientifically prove any of this, but that didn't matter to her.Before anything else, she would size up the ears of the person she was talking to.",
    "I've rented a car in Las Vegas and have reserved a hotel in Twentynine Palms which is just north of Joshua Tree. We'll drive from Las Vegas through Mojave National Preserve and possibly do a short hike on our way down.Then spend all day on Monday at Joshua Tree.We can decide the next morning if we want to do more in Joshua Tree or Mojave before we head back.",
    "There wasn't a whole lot he could do at that moment. He played the situation again and again in his head looking at what he might have done differently to make the situation better. No matter how many times he relived the situation in his head, there was never really a good alternative course of action. There simply wasn't a whole lot he could have done in that particular moment.",
    "Spending time at national parks can be an exciting adventure, but this wasn't the type of excitement she was hoping to experience. As she contemplated the situation she found herself in, she knew she'd gotten herself in a little more than she bargained for.It wasn't often that she found herself in a tree staring down at a pack of wolves that were looking to make her their next meal.",
    "Here's the thing. She doesn't have anything to prove, but she is going to anyway.That's just her character. She knows she doesn't have to, but she still will just to show you that she can.Doubt her more and she'll prove she can again. We all already know this and you will too.",
    "It had been her dream for years but Dana had failed to take any action toward making it come true.There had always been a good excuse to delay or prioritize another project.As she woke, she realized she was once again at a crossroads.Would it be another excuse or would she finally find the courage to pursue her dream ? Dana rose and took her first step.",
    "Sometimes it's the first moment of the day that catches you off guard. That's what Wendy was thinking.She opened her window to see fire engines screeching down the street.While this wasn't something completely unheard of, it also wasn't normal.It was a sure sign of what was going to happen that day.She could feel it in her bones and it wasn't the way she wanted the day to begin.",
    "The red ball sat proudly at the top of the toybox.It had been the last to be played with and anticipated it would be the next as well.The other toys grumbled beneath.At one time each had held the spot of the red ball, but over time they had sunk deeper and deeper into the toy box.",
    "There are only three ways to make this work.The first is to let me take care of everything.The second is for you to take care of everything.The third is to split everything 50 / 50. I think the last option is the most preferable, but I'm certain it'll also mean the end of our marriage.",
    "Indescribable oppression, which seemed to generate in some unfamiliar part of her consciousness, filled her whole being with a vague anguish.It was like a shadow, like a mist passing across her soul's summer day. It was strange and unfamiliar; it was a mood.",
    "She did not sit there inwardly upbraiding her husband, lamenting at Fate, which had directed her footsteps to the path which they had taken. She was just having a good cry all to herself. The mosquitoes made merry over her, biting her firm, round arms and nipping at her bare insteps.",
    "His mother had always taught him not to ever think of himself as better than others.He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
    "It all started with a random letter.Several of those were joined forces to create a random word.The words decided to get together and form a random sentence.They decided not to stop there and it wasn't long before a random paragraph had been cobbled together. The question was whether or not they could continue the momentum long enough to create a random short story.",
    "It was a simple green chair.There was nothing extraordinary about it or so it seemed.It was the type of chair one would pass without even noticing it was there, let alone what the actual color of it was.It was due to this common and unassuming appearance that few people actually stopped to sit in it and discover its magical powers.",
    "Eating raw fish didn't sound like a good idea. It's a delicacy in Japan, It didn't seem to make it any more appetizing. Raw fish is raw fish, delicacy or not.",
    "The water rush down the wash and into the slot canyon below.Two hikers had started the day to sunny weather without a cloud in the sky, but they hadn't thought to check the weather north of the canyon. Huge thunderstorms had brought a deluge o rain and produced flash floods heading their way. The two hikers had no idea what was coming.",
    "There was a leak in the boat.Nobody had yet noticed it, and nobody would for the next couple of hours.This was a problem since the boat was heading out to sea and while the leak was quite small at the moment, it would be much larger when it was ultimately discovered.John had planned it exactly this way.",
    "It wasn't that he hated her. It was simply that he didn't like her much.It was difficult for him to explain this to her, and even more difficult for her to truly understand.She was in love and wanted him to feel the same way.He didn't, and no matter how he tried to explain to her she refused to listen or to understand.",
    "It was supposed to be a dream vacation.They had planned it over a year in advance so that it would be perfect in every way.It had been what they had been looking forward to through all the turmoil and negativity around them.It had been the light at the end of both their tunnels.Now that the dream vacation was only a week away, the virus had stopped all air travel."




]
export default text